export const albumData = {
  hallOfFame: [
    {
      artist: 'The National',
      coverUrl: '/album-art/the-national-high-violet.jpg',
      name: 'High Violet',
      yearReleased: 2010,
    },
    {
      artist: 'Other Lives',
      coverUrl: '/album-art/other-lives-tamer-animals.jpg',
      name: 'Tamer Animals',
      yearReleased: 2011,
    },
    {
      artist: 'Sufjan Stevens',
      coverUrl: '/album-art/carrie-lowell-sufjan-stevens.jpg',
      name: 'Carrie & Lowell',
      yearReleased: 2015,
    },
    {
      artist: 'White Lies',
      coverUrl: '/album-art/white-lies-ritual.jpg',
      name: 'Ritual',
      yearReleased: 2011,
    },
  ],
  favorites: [
    [
      {
        artist: 'Lorn',
        coverUrl: '/album-art/lorn-maze-to-nowhere.jpg',
        name: 'The Maze to Nowhere',
        yearDiscovered: 2022,
        yearReleased: 2014,
      },
    ],
    [
      {
        artist: 'Hælos',
        coverUrl: '/album-art/haelos-full-circle.jpg',
        name: 'Full Circle',
        yearDiscovered: 2021,
        yearReleased: 2016,
      },
    ],
    [
      {
        artist: 'Poliça',
        coverUrl: '/album-art/polica-warrior-lord.jpg',
        name: 'Warrior Lord',
        yearDiscovered: 2020,
        yearReleased: 2013,
      },
      {
        artist: 'Warpaint',
        coverUrl: '/album-art/warpaint-warpaint.jpg',
        name: 'Warpaint',
        yearDiscovered: 2020,
        yearReleased: 2014,
      },
      {
        artist: 'Raury',
        coverUrl: '/album-art/raury-indigo-child.jpg',
        name: 'Indigo Child - EP',
        yearDiscovered: 2020,
        yearReleased: 2014,
      },
    ],
    [
      {
        artist: 'Caveman',
        coverUrl: '/album-art/caveman-otero-war.jpg',
        name: 'Otero War',
        yearDiscovered: 2019,
        yearReleased: 2016,
      },
      {
        artist: 'Luluc',
        coverUrl: '/album-art/luluc-passerby.jpg',
        name: 'Passerby',
        yearDiscovered: 2019,
        yearReleased: 2014,
      },
      {
        artist: 'Swimware',
        coverUrl: '/album-art/swimware-algorithm-nation.jpg',
        name: 'Algorithm Nation',
        yearDiscovered: 2019,
        yearReleased: 2018,
      },
    ],
    [
      {
        artist: 'Frightened Rabbit',
        coverUrl: '/album-art/frightened-rabbit-painting-of-a-panic-attack.jpg',
        name: 'Painting of a Panic Attack',
        yearDiscovered: 2018,
        yearReleased: 2016,
      },
      {
        artist: 'Tangerine Dream',
        coverUrl: '/album-art/tangerine-dream-exit.jpg',
        name: 'Exit',
        yearDiscovered: 2018,
        yearReleased: 1981,
      },
      {
        artist: 'Chromatics',
        coverUrl: '/album-art/chromatics-night-drive.jpg',
        name: 'Night Drive',
        yearDiscovered: 2018,
        yearReleased: 2007,
      },
    ],
    [
      {
        artist: 'Portugal. The Man',
        coverUrl: '/album-art/portugal-the-man-woodstock.jpg',
        name: 'Woodstock',
        yearDiscovered: 2017,
        yearReleased: 2017,
      },
      {
        artist: 'Cold War Kids',
        coverUrl: '/album-art/cold-war-kids-la-divine.jpg',
        name: 'LA DIVINE',
        yearDiscovered: 2017,
        yearReleased: 2017,
      },
      {
        artist: 'Austra',
        coverUrl: '/album-art/austra-future-politics.jpg',
        name: 'Future Politics',
        yearDiscovered: 2017,
        yearReleased: 2017,
      },
    ],
    [
      {
        artist: 'Sufjan Stevens',
        coverUrl: '/album-art/carrie-lowell-sufjan-stevens.jpg',
        name: 'Carrie & Lowell',
        yearDiscovered: 2016,
        yearReleased: 2015,
      },
      {
        artist: 'RIVKA',
        coverUrl: '/album-art/rivka-faded-ep.jpg',
        name: 'Faded (EP)',
        yearDiscovered: 2016,
        yearReleased: 2013,
      },
      {
        artist: 'M83',
        coverUrl: '/album-art/m83-junk.jpg',
        name: 'Junk',
        yearDiscovered: 2016,
        yearReleased: 2016,
      },
    ],
    [
      {
        artist: 'Emancipator',
        coverUrl: '/album-art/emancipator-soon-it-will-be-cold-enough.jpg',
        name: 'Soon It Will Be Cold Enough',
        yearDiscovered: 2015,
        yearReleased: 2006,
      },
      {
        artist: 'Lana Del Rey',
        coverUrl: '/album-art/lana-del-rey-ultraviolence.jpg',
        name: 'Ultraviolence',
        yearDiscovered: 2014,
        yearReleased: 2014,
      },
    ],
    [
      {
        artist: 'Fka Twigs',
        coverUrl: '/album-art/fka-twigs-lp1.jpg',
        name: 'Lp1',
        yearDiscovered: 2014,
        yearReleased: 2014,
      },
      {
        artist: 'Rõyksopp & Robyn',
        coverUrl: '/album-art/royksopp-and-robyn-do-it-again.jpg',
        name: 'Do It Again',
        yearDiscovered: 2014,
        yearReleased: 2014,
      },
    ],
    [
      {
        artist: 'Cold War Kids',
        coverUrl: '/album-art/cold-war-kids-dear-miss-lonelyhearts.jpg',
        name: 'Dear Miss Lonelyhearts',
        yearDiscovered: 2013,
        yearReleased: 2013,
      },
      {
        artist: 'Daft Punk',
        coverUrl: '/album-art/daft-punk-random-access-memories.jpg',
        name: 'Random Access Memories',
        yearDiscovered: 2013,
        yearReleased: 2013,
      },
    ],
    [
      {
        artist: 'Silversun Pickups',
        coverUrl: '/album-art/silversun-pickups-neck-of-the-woods.jpg',
        name: 'Neck Of The Woods',
        yearDiscovered: 2012,
        yearReleased: 2012,
      },
    ],
    [
      {
        artist: 'Other Lives',
        coverUrl: '/album-art/other-lives-tamer-animals.jpg',
        name: 'Tamer Animals',
        yearDiscovered: 2011,
        yearReleased: 2011,
      },
      {
        artist: 'M83',
        coverUrl: '/album-art/m83-hurry-up-were-dreaming.jpg',
        name: "Hurry Up, We're Dreaming",
        yearDiscovered: 2011,
        yearReleased: 2011,
      },
      {
        artist: 'Gotye',
        coverUrl: '/album-art/gotye-making-mirrors.jpg',
        name: 'Making Mirrors',
        yearDiscovered: 2011,
        yearReleased: 2011,
      },
      {
        artist: 'White Lies',
        coverUrl: '/album-art/white-lies-ritual.jpg',
        name: 'Ritual',
        yearDiscovered: 2011,
        yearReleased: 2011,
      },
      {
        artist: 'Feist',
        coverUrl: '/album-art/feist-metals.jpg',
        name: 'Metals',
        yearDiscovered: 2011,
        yearReleased: 2011,
      },
    ],
    [
      {
        artist: 'The National',
        coverUrl: '/album-art/the-national-high-violet.jpg',
        name: 'High Violet',
        yearDiscovered: 2010,
        yearReleased: 2010,
      },
      {
        artist: 'Bon Iver',
        coverUrl: '/album-art/bon-iver-for-emma-forever-ago.jpg',
        name: 'For Emma, Forever Ago',
        yearDiscovered: 2010,
        yearReleased: 2007,
      },
      {
        artist: 'Ratatat',
        coverUrl: '/album-art/ratatat-lp4.jpg',
        name: 'LP4',
        yearDiscovered: 2010,
        yearReleased: 2010,
      },
      {
        artist: 'Daft Punk',
        coverUrl: '/album-art/daft-punk-tron-legacy-soundtrack.jpg',
        name: 'TRON: Legacy',
        yearDiscovered: 2010,
        yearReleased: 2010,
      },
    ],
    [
      {
        artist: 'Fever Ray',
        coverUrl: '/album-art/fever-ray-fever-ray.jpg',
        name: 'Fever Ray',
        yearDiscovered: 2009,
        yearReleased: 2009,
      },
    ],
    [
      {
        artist: 'M83',
        coverUrl: '/album-art/m83-saturdays-equals-youth.jpg',
        name: 'Saturdays = Youth',
        yearDiscovered: 2008,
        yearReleased: 2008,
      },
    ],
    [
      {
        artist: 'Interpol',
        coverUrl: '/album-art/interpol-our-love-to-admire.jpg',
        name: 'Our Love to Admire',
        yearDiscovered: 2007,
        yearReleased: 2007,
      },
    ],
    [
      {
        artist: 'Rõyksopp',
        coverUrl: '/album-art/royksopp-the-understanding.jpg',
        name: 'The Understanding',
        yearDiscovered: 2005,
        yearReleased: 2005,
      },
    ],
    [
      {
        artist: 'Moby',
        coverUrl: '/album-art/moby-play.jpg',
        name: 'Play',
        yearDiscovered: 2004,
        yearReleased: 2004,
      },
    ],
    [
      {
        artist: 'AFI',
        coverUrl: '/album-art/afi-sing-the-sorrow.jpg',
        name: 'Sing the Sorrow',
        yearDiscovered: 2003,
        yearReleased: 2003,
      },
    ],
    [
      {
        artist: 'Sigur Rós',
        coverUrl: '/album-art/sigur-ros-().jpg',
        name: '()',
        yearDiscovered: 2002,
        yearReleased: 2002,
      },
    ],
    [
      {
        artist: 'Tori Amos',
        coverUrl: '/album-art/tori-amos-from-the-choir-girl-hotel.jpg',
        name: 'From the Choir Girl Hotel',
        yearDiscovered: 2001,
        yearReleased: 1998,
      },
      {
        artist: 'Inside',
        coverUrl: '/album-art/inside-my-funeral.jpg',
        name: 'My Funeral',
        yearDiscovered: 2001,
        yearReleased: 1998,
      },
      {
        artist: 'Jimmy Eat World',
        coverUrl: '/album-art/jimmy-eat-world-bleed-american.jpg',
        name: 'Bleed American',
        yearDiscovered: 2001,
        yearReleased: 2001,
      },
      {
        artist: 'The Killingtons',
        coverUrl: '/album-art/the-killingtons.jpg',
        name: 'The Killingtons',
        yearDiscovered: 2001,
        yearReleased: 2000,
      },
      {
        artist: 'Travis',
        coverUrl: '/album-art/travis-the-invisible-band.jpg',
        name: 'The Invisible Band',
        yearDiscovered: 2001,
        yearReleased: 2001,
      },
    ],
  ],
}
